# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 13:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('original_image', models.ImageField(upload_to='images/')),
                ('edited_image', models.ImageField(blank=True, upload_to='edited/')),
                ('size', models.CharField(blank=True, max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('category', models.IntegerField(choices=[(1, 'Selfies'), (2, 'Music'), (3, 'Fashion'), (4, 'Party'), (5, 'Sports'), (6, 'Adventure'), (7, 'Miscellanous'), (8, 'School'), (9, 'Holiday'), (10, 'Hobby')], default=9)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
