# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='size',
        ),
        migrations.RemoveField(
            model_name='image',
            name='uploader',
        ),
    ]
