# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 00:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20160803_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='edited_image',
        ),
    ]
